global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['188.166.166.64:9100']
  - job_name: 'mysql'
    scrape_interval: 5s
    static_configs:
      - targets: ['188.166.166.64:9104']
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['188.166.166.64:8080']



